# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Tasuki' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#  use_frameworks!

  # Pods for Tasuki
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'TouchID', :path => '../node_modules/react-native-touch-id'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

end
